<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Ymm4TemplatePlacer</AssemblyName>
    <RootNamespace>Ymm4TemplatePlacer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="YukkuriMovieMaker.Plugin">
      <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
